import type { UsageMeasures } from "../UsageTypes.js";
import table from "./ecologits.json" with { type: "json" };

/**
 * Environmental impacts of AI usage, from EcoLogits coefficients exported into
 * ecologits.json by scripts/ecologits/export.py (see docs/ai-footprint-meter.md).
 *
 * EcoLogits models one request as linear in output tokens and generation time, and
 * generation time is capped by what was actually measured:
 *
 *   generation = min(request seconds, tokens × seconds per token + requests × first-token seconds)
 *   impact     = per token × tokens + per generation second × generation
 */

export const IMPACTS = ["energy", "gwp", "adpe", "pe", "wcf"] as const;
export type Impact = typeof IMPACTS[number];

/** kWh, kgCO2eq, kgSbeq, MJ, L — EcoLogits' own units. */
export const IMPACT_UNITS: Record<Impact, string> = table.units;

export interface ImpactRange {
    low: number;
    high: number;
}

export type Impacts = Record<Impact, ImpactRange>;

interface RangeEnd {
    secondsPerToken: number;
    firstTokenSeconds: number;
    perToken: Record<Impact, number>;
    perGenerationSecond: Record<Impact, number>;
}

export interface EcologitsModel {
    ecologitsModel: string | null;
    usageMeasure: "output_tokens" | "audio_seconds";
    tokensPerUnit: number;
    datacenterZone: string;
    low: RangeEnd;
    high: RangeEnd;
    assumptions: string[];
    warnings: string[];
    sources: string[];
}

export const ECOLOGITS_VERSION: string = table.ecologitsVersion;

export interface EcologitsSample {
    units: number;
    requestSeconds: number | null;
    impacts: Record<Impact, [number, number]>;
}

// Generated by the export script; the golden-sample test holds its shape to these types.
const models = table.models as unknown as Record<string, EcologitsModel & { samples: EcologitsSample[] }>;

/** The EcoLogits entry for a recorded provider and model, if one has been exported. */
export function findEcologitsModel(provider: string, model: string): EcologitsModel | undefined {
    return models[`${provider}|${model}`];
}

export interface UsageSummary {
    /** Summed raw measures, as stored in usage totals. */
    measures: UsageMeasures;
    /** How many requests the measures cover. */
    requests: number;
}

function estimateEnd(end: RangeEnd, tokens: number, requests: number, requestSeconds: number): Record<Impact, number> {
    const generationSeconds = Math.min(requestSeconds, tokens * end.secondsPerToken + requests * end.firstTokenSeconds);
    const impacts = {} as Record<Impact, number>;
    for (const impact of IMPACTS) {
        impacts[impact] = end.perToken[impact] * tokens + end.perGenerationSecond[impact] * generationSeconds;
    }
    return impacts;
}

export function estimateImpacts(model: EcologitsModel, usage: UsageSummary): Impacts {
    const tokens = (usage.measures[model.usageMeasure] ?? 0) * model.tokensPerUnit;
    const requestSeconds = usage.measures.request_seconds ?? Number.POSITIVE_INFINITY;
    const low = estimateEnd(model.low, tokens, usage.requests, requestSeconds);
    const high = estimateEnd(model.high, tokens, usage.requests, requestSeconds);

    const impacts = {} as Impacts;
    for (const impact of IMPACTS) {
        impacts[impact] = { low: low[impact], high: high[impact] };
    }
    return impacts;
}

/** Every exported model, for the methodology page and tests. */
export function listEcologitsModels(): [string, EcologitsModel][] {
    return Object.entries(models);
}

/** EcoLogits' own results for fixed inputs, exported next to the coefficients. */
export function ecologitsSamples(key: string): EcologitsSample[] {
    return models[key]?.samples ?? [];
}
