import type { UsageMeasures } from "../UsageTypes.js";
import table from "./ecologits.json" with { type: "json" };

/**
 * Environmental impacts of AI usage, from EcoLogits coefficients exported into
 * ecologits.json by scripts/ecologits/export.py (see docs/ai-footprint-meter.md).
 *
 * EcoLogits models one request as linear in output tokens and generation time, and
 * generation time is capped by what was actually measured:
 *
 *   generation = min(request seconds, tokens × seconds per token + requests × first-token seconds)
 *   impact     = per token × tokens + per generation second × generation
 */

export const IMPACTS = ["energy", "gwp", "adpe", "pe", "wcf"] as const;
export type Impact = typeof IMPACTS[number];

/** kWh, kgCO2eq, kgSbeq, MJ, L — EcoLogits' own units. */
export const IMPACT_UNITS: Record<Impact, string> = table.units;

export interface ImpactRange {
    low: number;
    high: number;
}

export type Impacts = Record<Impact, ImpactRange>;

interface RangeEnd {
    secondsPerToken: number;
    firstTokenSeconds: number;
    perToken: Record<Impact, number>;
    perGenerationSecond: Record<Impact, number>;
}

export interface EcologitsModel {
    ecologitsModel: string | null;
    usageMeasure: "output_tokens" | "audio_seconds";
    tokensPerUnit: number;
    datacenterZone: string;
    low: RangeEnd;
    high: RangeEnd;
    assumptions: string[];
    warnings: string[];
    sources: string[];
}

export const ECOLOGITS_VERSION: string = table.ecologitsVersion;

export interface EcologitsSample {
    units: number;
    requestSeconds: number | null;
    impacts: Record<Impact, [number, number]>;
}

// Generated by the export script; the golden-sample test holds its shape to these types.
const models = table.models as unknown as Record<string, EcologitsModel & { samples: EcologitsSample[] }>;

/** The EcoLogits entry for a recorded provider and model, if one has been exported. */
export function findEcologitsModel(provider: string, model: string): EcologitsModel | undefined {
    return models[`${provider}|${model}`];
}

export interface UsageSummary {
    /** Summed raw measures, as stored in usage totals. */
    measures: UsageMeasures;
    /** How many requests the measures cover. */
    requests: number;
}

/**
 * EcoLogits for `requests` requests totalling `units`, with generation time capped at
 * `capSeconds` — exactly EcoLogits' own result when the cap is the measured request latency.
 */
export function estimateEcologitsImpacts(
    model: EcologitsModel,
    units: number,
    requests: number,
    capSeconds: number,
): Impacts {
    const tokens = units * model.tokensPerUnit;
    const impacts = {} as Impacts;
    const ends = { low: model.low, high: model.high };
    const generationSeconds = {
        low: Math.min(capSeconds, tokens * ends.low.secondsPerToken + requests * ends.low.firstTokenSeconds),
        high: Math.min(capSeconds, tokens * ends.high.secondsPerToken + requests * ends.high.firstTokenSeconds),
    };
    for (const impact of IMPACTS) {
        impacts[impact] = {
            low: ends.low.perToken[impact] * tokens + ends.low.perGenerationSecond[impact] * generationSeconds.low,
            high: ends.high.perToken[impact] * tokens + ends.high.perGenerationSecond[impact] * generationSeconds.high,
        };
    }
    return impacts;
}

/**
 * Impacts of summed usage for one model.
 *
 * Measured request time is not used: the same model is called both with it (server calls)
 * and without it (realtime sessions), so a summed request time would cover only some of the
 * tokens. Generation time comes from EcoLogits' latency model instead (published tokens per
 * second where known). For audio models that model is an LLM regression far slower than any
 * streaming voice, so generation is capped at the audio's own length: streamed speech and
 * transcription must run at least as fast as real time.
 */
export function estimateImpacts(model: EcologitsModel, usage: UsageSummary): Impacts {
    const units = usage.measures[model.usageMeasure] ?? 0;
    const capSeconds = model.usageMeasure === "audio_seconds" ? units : Number.POSITIVE_INFINITY;
    return estimateEcologitsImpacts(model, units, usage.requests, capSeconds);
}

/** Every exported model, for the methodology page and tests. */
export function listEcologitsModels(): [string, EcologitsModel][] {
    return Object.entries(models);
}

/** EcoLogits' own results for fixed inputs, exported next to the coefficients. */
export function ecologitsSamples(key: string): EcologitsSample[] {
    return models[key]?.samples ?? [];
}
