import type { UsageMeasures } from "../UsageTypes.js";
import table from "./ecologits.json" with { type: "json" };

/**
 * Environmental impacts of AI usage, from EcoLogits coefficients exported into
 * ecologits.json by scripts/ecologits/export.py (see docs/ai-footprint-meter.md).
 *
 * EcoLogits models one request as linear in output tokens and generation time:
 *
 *   generation = min(cap, tokens × seconds per token + requests × first-token seconds)
 *   impact     = per token × tokens + per generation second × generation
 *
 * The cap is the measured request time in EcoLogits itself; see estimateImpacts for ours.
 */

/** Energy (kWh), carbon (kgCO2eq), minerals (kgSbeq) and water (L), in EcoLogits' own units. */
export const IMPACTS = ["energy", "gwp", "adpe", "wcf"] as const;
export type Impact = typeof IMPACTS[number];

export interface ImpactRange {
    low: number;
    high: number;
}

export type Impacts = Record<Impact, ImpactRange>;

interface RangeEnd {
    secondsPerToken: number;
    firstTokenSeconds: number;
    perToken: Record<Impact, number>;
    perGenerationSecond: Record<Impact, number>;
    /** The part of perGenerationSecond that is hardware manufacturing (EcoLogits' embodied impacts). */
    embodiedPerGenerationSecond: Record<Impact, number>;
    /** GPUs the model needs, shared by a batch of `HARDWARE.batchSize` requests. */
    gpus: number;
}

/**
 * What a model does at the council, as far as counting goes: which of the meter's tallies its
 * usage adds to. The word visitors see can differ (client/src/meter/modelInfo.ts).
 */
export type ModelRole = "writing" | "speaking" | "listening";

/**
 * How much is known about a model: EcoLogits' own entry, EcoLogits' method on a published size
 * where its entry is wrong, or EcoLogits' method on our analogy where nothing is published.
 */
export type ModelBasis = "ecologits" | "corrected" | "guessed";

export interface EcologitsModel {
    role: ModelRole;
    basis: ModelBasis;
    usageMeasure: "output_tokens" | "audio_seconds";
    tokensPerUnit: number;
    /** Where it may run (EcoLogits' zones); with more than one, the range spans them. */
    datacenterZones: string[];
    /** Billions, [low, high]. */
    activeParameters: [number, number];
    totalParameters: [number, number];
    low: RangeEnd;
    high: RangeEnd;
    assumptions: string[];
    warnings: string[];
    sources: string[];
}

export const ECOLOGITS_VERSION: string = table.ecologitsVersion;

/** EcoLogits' fixed hardware assumptions: one GPU type, requests batched, a 3-year life. */
export const HARDWARE: { gpu: string; batchSize: number; lifetimeSeconds: number } = table.hardware;

export interface EcologitsSample {
    units: number;
    requestSeconds: number | null;
    impacts: Record<Impact, [number, number]>;
    manufacturing: Record<Impact, [number, number]>;
}

// Generated by the export script; the golden-sample test holds its shape to these types.
const models = table.models as unknown as Record<string, EcologitsModel & { samples: EcologitsSample[] }>;

/** The EcoLogits entry for a recorded provider and model, if one has been exported. */
export function findEcologitsModel(provider: string, model: string): EcologitsModel | undefined {
    return models[`${provider}|${model}`];
}

export interface UsageSummary {
    /** Summed raw measures, as stored in usage totals. */
    measures: UsageMeasures;
    /** How many requests the measures cover. */
    requests: number;
}

function generationSeconds(end: RangeEnd, tokens: number, requests: number, capSeconds: number): number {
    return Math.min(capSeconds, tokens * end.secondsPerToken + requests * end.firstTokenSeconds);
}

/**
 * EcoLogits for `requests` requests totalling `units`, with generation time capped at
 * `capSeconds` — exactly EcoLogits' own result when the cap is the measured request latency.
 */
export function estimateEcologitsImpacts(
    model: EcologitsModel,
    units: number,
    requests: number,
    capSeconds: number,
): Impacts {
    const tokens = units * model.tokensPerUnit;
    const at = (end: RangeEnd, impact: Impact) =>
        end.perToken[impact] * tokens + end.perGenerationSecond[impact] * generationSeconds(end, tokens, requests, capSeconds);
    return Object.fromEntries(
        IMPACTS.map((impact) => [impact, { low: at(model.low, impact), high: at(model.high, impact) }]),
    ) as Impacts;
}

/**
 * Units and generation-time cap for summed usage of one model.
 *
 * Measured request time is not used: the same model is called both with it (server calls)
 * and without it (realtime sessions), so a summed request time would cover only some of the
 * tokens. Generation time comes from EcoLogits' latency model instead (published tokens per
 * second where known). For audio models that model is an LLM regression far slower than any
 * streaming voice, so generation is capped at the audio's own length: streamed speech and
 * transcription must run at least as fast as real time.
 */
function unitsAndCap(model: EcologitsModel, usage: UsageSummary): [units: number, capSeconds: number] {
    const units = usage.measures[model.usageMeasure] ?? 0;
    return [units, model.usageMeasure === "audio_seconds" ? units : Number.POSITIVE_INFINITY];
}

/** Impacts of summed usage for one model. */
export function estimateImpacts(model: EcologitsModel, usage: UsageSummary): Impacts {
    const [units, capSeconds] = unitsAndCap(model, usage);
    return estimateEcologitsImpacts(model, units, usage.requests, capSeconds);
}

/** The hardware-manufacturing part of `estimateEcologitsImpacts`, as EcoLogits reports it (embodied impacts). */
export function estimateEcologitsManufacturing(
    model: EcologitsModel,
    units: number,
    requests: number,
    capSeconds: number,
): Impacts {
    const tokens = units * model.tokensPerUnit;
    const at = (end: RangeEnd, impact: Impact) =>
        end.embodiedPerGenerationSecond[impact] * generationSeconds(end, tokens, requests, capSeconds);
    return Object.fromEntries(
        IMPACTS.map((impact) => [impact, { low: at(model.low, impact), high: at(model.high, impact) }]),
    ) as Impacts;
}

/** The hardware-manufacturing part of `estimateImpacts`: zero for energy and water, which EcoLogits counts only in use. */
export function estimateManufacturing(model: EcologitsModel, usage: UsageSummary): Impacts {
    const [units, capSeconds] = unitsAndCap(model, usage);
    return estimateEcologitsManufacturing(model, units, usage.requests, capSeconds);
}

/**
 * GPU time a model's usage occupied, as seconds of one whole GPU: the model's GPUs work for the
 * generation time on a batch of requests, and each request's share is one batch place. This is
 * what EcoLogits divides each GPU's and server's manufacturing footprint by.
 */
export function estimateGpuSeconds(model: EcologitsModel, usage: UsageSummary): ImpactRange {
    const [units, capSeconds] = unitsAndCap(model, usage);
    const tokens = units * model.tokensPerUnit;
    const at = (end: RangeEnd) => (generationSeconds(end, tokens, usage.requests, capSeconds) * end.gpus) / HARDWARE.batchSize;
    return { low: at(model.low), high: at(model.high) };
}

/** Every exported model, for the methodology page and tests. */
export function listEcologitsModels(): [string, EcologitsModel][] {
    return Object.entries(models);
}

/** EcoLogits' own results for fixed inputs, exported next to the coefficients. */
export function ecologitsSamples(key: string): EcologitsSample[] {
    return models[key]?.samples ?? [];
}
