import express, { type Express, type Request, type Response } from "express";
import { config } from "../config.js";
import { Logger } from "@utils/Logger.js";
import { withNetworkRetry } from "@utils/NetworkUtils.js";

/**
 * Server-side proxy for the Inworld Realtime API used by the NewMeeting voice guide.
 *
 * Why a proxy and not an ephemeral client token?
 * Inworld's Realtime API does not currently expose an OpenAI-style ephemeral
 * `client_secret` mint. The two supported auth modes are Basic auth with the
 * raw API key (server-only) and a HMAC-SHA256 JWT generated by your backend.
 * Proxying just the SDP exchange is the simplest pattern that keeps
 * `INWORLD_API_KEY` server-side and works identically for the museum kiosk and
 * the public website. After the SDP exchange, the WebRTC peer connection is
 * direct between the browser and Inworld's media servers, so this proxy is not
 * on the hot path for audio.
 *
 * Endpoints registered by `registerVoiceGuideRoutes`:
 *  - GET  /api/voice-guide/ice-servers : Inworld STUN/TURN config (JSON)
 *  - POST /api/voice-guide/session     : forwards an SDP offer (text) and returns the SDP answer (text)
 */

const INWORLD_BASE = "https://api.inworld.ai";
const INWORLD_REALTIME_CALLS_URL = `${INWORLD_BASE}/v1/realtime/calls`;
const INWORLD_ICE_SERVERS_URL = `${INWORLD_BASE}/v1/realtime/ice-servers`;

const SDP_BODY_LIMIT = "100kb";

export interface IceServer {
    urls: string[] | string;
    username?: string;
    credential?: string;
}

export interface IceServersResponse {
    iceServers: IceServer[];
}

/** Fetch Inworld's STUN/TURN servers so the browser can seed `RTCPeerConnection` before generating an offer. */
export async function getInworldIceServers(): Promise<IceServersResponse> {
    const response = await withNetworkRetry(
        () =>
            fetch(INWORLD_ICE_SERVERS_URL, {
                method: "GET",
                headers: {
                    Authorization: `Bearer ${config.INWORLD_API_KEY}`,
                },
            }),
        "voiceGuideSession.iceServers"
    );

    if (!response.ok) {
        const text = await response.text();
        throw new Error(`Inworld /v1/realtime/ice-servers failed (${response.status}): ${text}`);
    }

    const data = (await response.json()) as { ice_servers?: IceServer[] };
    return { iceServers: Array.isArray(data.ice_servers) ? data.ice_servers : [] };
}

/**
 * Forward an SDP offer to Inworld and return the SDP answer.
 * Inworld accepts the offer as `application/sdp` (raw body) and replies in kind.
 */
export async function exchangeSdpWithInworld(sdpOffer: string): Promise<string> {
    if (typeof sdpOffer !== "string" || sdpOffer.trim().length === 0) {
        throw new Error("SDP offer must be a non-empty string");
    }

    const response = await withNetworkRetry(
        () =>
            fetch(INWORLD_REALTIME_CALLS_URL, {
                method: "POST",
                headers: {
                    Authorization: `Bearer ${config.INWORLD_API_KEY}`,
                    "Content-Type": "application/sdp",
                },
                body: sdpOffer,
            }),
        "voiceGuideSession.sdp"
    );

    if (!response.ok) {
        const text = await response.text();
        throw new Error(`Inworld /v1/realtime/calls failed (${response.status}): ${text}`);
    }

    const sdpAnswer = await response.text();
    if (sdpAnswer.trim().length === 0) {
        throw new Error("Inworld /v1/realtime/calls returned an empty SDP answer");
    }

    return sdpAnswer;
}

/** Wires the voice-guide proxy endpoints onto the express app. */
export function registerVoiceGuideRoutes(app: Express): void {
    app.get("/api/voice-guide/ice-servers", async (_req: Request, res: Response) => {
        try {
            const data = await getInworldIceServers();
            res.status(200).json(data);
        } catch (e) {
            await Logger.error("api", "GET /api/voice-guide/ice-servers failed", e);
            res.status(500).json({ message: "Voice guide unavailable" });
        }
    });

    app.post(
        "/api/voice-guide/session",
        express.text({ type: ["application/sdp", "text/plain"], limit: SDP_BODY_LIMIT }),
        async (req: Request, res: Response) => {
            const sdpOffer = typeof req.body === "string" ? req.body : "";
            if (sdpOffer.trim().length === 0) {
                res.status(400).json({ message: "SDP offer required" });
                return;
            }

            try {
                const sdpAnswer = await exchangeSdpWithInworld(sdpOffer);
                res.status(200).type("application/sdp").send(sdpAnswer);
            } catch (e) {
                await Logger.error("api", "POST /api/voice-guide/session failed", e);
                res.status(500).json({ message: "Voice guide unavailable" });
            }
        }
    );
}
